# pytest.ini
[pytest]
# Make pytest-asyncio manage the event loop correctly
asyncio_mode = auto

# Always show full logs
log_cli = true
log_cli_level = INFO

# Make pytest find tests in "tests/" folder
testpaths = 
    tests

# Match test file patterns
python_files = test_*.py *_test.py
python_classes = Test* 
python_functions = test_*

# Treat warnings as non-fatal
filterwarnings =
    ignore::DeprecationWarning
    ignore::pytest.PytestUnraisableExceptionWarning
